### ISSUE TITLE
add optional parameter to translate enhancer

### ISSUE THREAD

**Issue by guillaumearm** [Tiqa/redux-polyglot#28]
translate enhancer could take a string named 'polyglotScope' to default browse in the phrases when use a `t` function : 

``` js
const TranslatedComponent = translate(DummyComponent, { polyglotScope: 'catalog.misc' })
```

but could be this : 

``` js
const TranslatedComponent = translate(DummyComponent, 'catalog.misc')
```

if you have a phrases object like : 

``` json
{
  "catalog": {
    "misc": {
      "hello": "hi"
    }
  }
}
```

you just need to do a `p.t('hello')`

**Comment by JalilArfaoui** [comment]
Must be optional and non-breaking

**Comment by guillaumearm** [comment]
ok for this 👍 
i will write unit tests soon, are you ok for publish it  on npmjs without 100% coverage and without documentation ?
![image](https://cloud.githubusercontent.com/assets/16897658/19239031/85c05c5a-8f04-11e6-8f07-668fe0b1d5b4.png)

**Comment by JalilArfaoui** [comment]
Well, coverage is still high and adoption is still low :-) ... I think you can publish.

**Comment by guillaumearm** [comment]
fixed in #29

**Comment by guillaumearm** [comment]
new implementation :

``` js
// all this lines return an enhanced Dummy component
translate(Dummy);
translate('catalog', Dummy);
translate('catalog')(Dummy);
```

I'm not a sure add an object instead of the string.
It's more simple like this ( to use and to code ).
@JalilArfaoui ?
@jvincent42  ?

**Comment by guillaumearm** [comment]
I just remove the possibility of passing an object because I really doesn't like this.

```
// too heavy
{ polyglotScope: 'scope' }
```

(see #29)

**Comment by guillaumearm** [comment]
#29 merged.
