### ISSUE TITLE
remove ramda from dependencies.

### ISSUE THREAD

**Issue by guillaumearm** [Tiqa/redux-polyglot#3]
remove ramda dependency.

just recode :
- R.path
- R.adjust
- R.toUpper
- R.join

don't forget to edit middleware.js and use `typeof` instead of `R.is`

> note: you can edit spy() function from middleware.spec.js, now he doesn't need his constructor mutation.

**Comment by jvincent42** [comment]
Possible to keep it in devDependencies ? for testing purpose in .spec.js files.

**Comment by guillaumearm** [comment]
sure ;-)

**Comment by guillaumearm** [comment]
need to complete #7 before do this (avoiding git conflict).
@JalilArfaoui, we need you.

**Comment by JalilArfaoui** [comment]
Merged !
