### ISSUE TITLE
exports translate() enhancer in a new module : react-redux-polyglot

### ISSUE THREAD

**Issue by guillaumearm** [Tiqa/redux-polyglot#37]
#### This is the main change on v1.0
- publish on npm directly in v1.0.0 ( same time as publishing redux-polyglot 1.0.0 )

**Comment by guillaumearm** [comment]
need close all v2 labeled issues before closing this.

**Comment by JalilArfaoui** [comment]
I have begin to write the react-redux-polyglot version (need answers on #48)

**Comment by guillaumearm** [comment]
it's ok 👍

**Comment by guillaumearm** [comment]
As we said, create one repo for 2 package.json ;-)
please see #59

**Comment by JalilArfaoui** [comment]
Can we close this one ?
