### ISSUE TITLE
translate can take an array of string

### ISSUE THREAD

**Issue by guillaumearm** [Tiqa/redux-polyglot#47]
today, `translate()` enhancer can select a polyglotScope giving a string.

why not give the possibility to provide many scopes in an array ?
- all scopes are merged into one. 
- all duplicate keys will be overwritten.

**Comment by guillaumearm** [comment]
utils : 

``` js
const mergeAll = t => t.reduce((mergedObj, obj) => Object.assign({}, mergedObj, obj), {})
```

**Comment by JalilArfaoui** [comment]
Nay ! If you need many scopes, you just don't pass any scope and access your keys directly as usual. 
IMHO polyglotScope must stay what it is ... a sugar.

**Comment by guillaumearm** [comment]
you're right, i close this issue.
