### ISSUE TITLE
dist folder should be pushed on github

### ISSUE THREAD

**Issue by guillaumearm** [Tiqa/redux-polyglot#53]
for allowing to install pre-releases with `npm install Tiqa/redux-polyglot`,
dist folder should be pushed.

take a look here : https://github.com/guillaumearm/redux-with-selectors/commit/8c220f4b36e62debaad684d1a476a1e79808e9eb

**Comment by guillaumearm** [comment]
PR here #56

**Comment by JalilArfaoui** [comment]
npm install @Tiqa/redux-polyglot is from scoped npm package, not from Github. 
Any other reason to include dist on repo @guillaumearm  ?

**Comment by guillaumearm** [comment]
sorry for the '@', just a mistake.

So about the dist folder, I recommend a postinstall script and build only when `dist` is missing to prevent for broken installation.

**Comment by JalilArfaoui** [comment]
Yes, as we discussed, I prefer the postinstall solution, which does not need us to version /dist.

**Comment by guillaumearm** [comment]
postinstall example script here: https://github.com/guillaumearm/redux-viewport/blob/master/scripts/postinstall.js
