### ISSUE TITLE
Support react-redux 5.x

### ISSUE THREAD

**Issue by anpieber** [Tiqa/redux-polyglot#65]
Currently 4.x is entered as a peer dependency. This does not really hurt, except that shrinkwrap does not like it if you're using react-redux 5 otherwise.

**Comment by JalilArfaoui** [comment]
You're right. We should check that using RR5 does not break anything, and then change dependency to accept 4 or 5.

**Comment by anpieber** [comment]
Using react-redux 5.x in my app worked like a charm. Upgrading redux-ployglot didn't introduced any new test failures for me. Looks fine :-)

**Comment by guillaumearm** [comment]
Good news, I will publish redux-polyglot 0.3.2 tomorrow about this :P

**Comment by guillaumearm** [comment]
#66 resolve this
note : 0.3.2 has been published on npm (latest)
