### ISSUE TITLE
Is there a way to set the onMissingKey and allowMissing property of Polyglot ?

### ISSUE THREAD

**Issue by tata9001** [Tiqa/redux-polyglot#67]

**Comment by guillaumearm** [comment]
Hmmm, i don't know, I will check for this tonight ;-)

**Comment by guillaumearm** [comment]
Nope, you can't.
it will be fixed very soon with a `createGetP` factory 👍

**Comment by tata9001** [comment]
Thanks! Waiting for it....

**Comment by guillaumearm** [comment]
please check for https://github.com/Tiqa/redux-polyglot/tree/feat/createGetP
is it ok for you ?

I don't want to push this without test on a real project.
Do you want a release candidate ?

**Comment by guillaumearm** [comment]
Need documentation about this before publish on `redux-polyglot@latest`

**Comment by tata9001** [comment]
I have already tested  it on my project.
It's ok for me.
Thanks!

**Comment by guillaumearm** [comment]
ok, i'll write documentation soon for this (maybe tonight).

**Comment by guillaumearm** [comment]
I'm thinking to add a function `setPolyglotOptions` to redux-polyglot.
even if you can create your own `getP`, I want to mutate `getP` polyglot options.

so you can import the basic `getP` function and use `setPolyglotOptions` once at the start of your app.
This is the easy way to change polyglot options.

`createGetP`is the pure alternative, very useful for unit testing.

@wangyun1517 @JalilArfaoui @jvincent42 ?
what do you think about ? :-)

example :
```js
import { setPolyglotOptions } from 'redux-polyglot';

const options = { allowMissing: true };
dispatch(setPolyglotOptions(options));
```

**Comment by guillaumearm** [comment]
Let's talk about this in #68.
Anyway, I just pre-release 0.4.0 on a `next` dist-tag ;-)

```bash
# to see available dist-tag
npm dist-tag ls redux-polyglot 

# install 0.4.0
npm install --save redux-polyglot@0.4.0
```
