### ISSUE TITLE
NPM warning with React 15.5.4

### ISSUE THREAD

**Issue by techrah** [Tiqa/redux-polyglot#83]
I am currently using React v15.5.4. Versions 15.5.0 to 15.5.3 are all deprecated due to a critical issue. However, using redux-polyglot@0.5.2 causes the following warning because it has react `'15.5.0'` (not `'^15.5.0'`) as a peer dependency:
```
redux-polyglot@0.5.2 requires a peer of react@15.5.0 but none was installed.
```
I believe redux-polyglot@0.5.2 is the first version to import PropTypes from prop-types and not from react so this seems to be the correct (and currently only) version to use with react@15.5.4.

So far, redux-polyglot seems to be working correctly with react@15.5.4 but I do not know if there was a particular reason for locking in the single peer dependency version.

**Comment by guillaumearm** [comment]
Hi, no there is no particular reason for locking peer dep react version, it's just a mistake.

I just release redux-polyglot@0.5.3

Thank you very much for reporting :-)
